const NOT_FOUND_ERROR = 404;
const BAD_REQUEST_ERROR = 400;
const INTERNAL_SERVER_ERROR = 500;
const OK_STATUS = 200;
const FORBIDDEN_ERROR = 403;

module.exports = {
  NOT_FOUND_ERROR, BAD_REQUEST_ERROR, INTERNAL_SERVER_ERROR, OK_STATUS, FORBIDDEN_ERROR,
};
